### ISSUE TITLE
Feature Request: 何时可以在仙3外上使用该补丁？

### ISSUE THREAD

**Issue by medivhna** [zhangboyang/PAL3patch#1]
仙剑3上效果很好，仙3外的引擎和仙3类似，不知目前开发进度如何？

**Comment by zhangboyang** [comment]
虽说3和3外在程序上比较类似，但是由于补丁是直接修改机器码，所以几乎相当于要重做一遍。现在的进度是刚把3外的壳借助破解补丁脱掉了，其他部分都还没有开始。

我现在比较担心问题是官方的重制版：如果重制版与原版的差异很大，那其实是无所谓的；现在就怕重制版与原版几乎没有差异，那就没有分辨率补丁存在的必要了。

**Comment by medivhna** [comment]
我不觉得他们会在PC上搞重制，最多放个手机版

北软似乎也有意无意在回避仙3~仙4的历史

**Comment by zhangboyang** [comment]
嗯。。我比较倾向于认为重制版会差异较大，但是我觉得可能会PC版和手机版都会有吧，感觉只做一个版本的话有点浪费资源。。。
目前计划三外的补丁会在今年年底或者明年年初发布。

**Comment by ukhack** [comment]
感激。在方块游戏平台上下载的“正版”仙剑奇侠传系列，在win10 1703全都不能运行。唯有装了你的补丁的仙剑3居然成功运行。希望大神能给我们带来更多的惊喜，代表众多的仙迷感谢了

**Comment by zhangboyang** [comment]
@ukhack 哈哈～我这边win10 1703运行方块的没有问题啊，我觉得可能有两个问题会导致你的情况：一个是windows defender有可能会把方块的启动器当成病毒杀掉；另一个问题就是，需要把数据执行保护（DEP）关掉，因为方块正版实际上是整合了游侠网的免cd补丁的，而那个补丁是没有考虑DEP的问题的。

**Comment by ukhack** [comment]
真是尴尬，我刚才试着关掉了DEP并重启了系统，发现系统流畅许多（我的错觉？）
但是游戏还是不能运行，双击是没有反应的，连游戏界面都看不到。

**Comment by ukhack** [comment]
看了下defender也是关闭状态。也跑去3dm装了运行库合集。如此就很是尴尬了

**Comment by zhangboyang** [comment]
DEP应该是不会影响速度的，可能是重启了一下所以变快了吧哈哈。如果关DEP没用那还是打开比较好，毕竟打开之后安全些。。方块的启动器是比较奇怪，我也不知道它里面做了什么，可能你遇到了某些奇怪的不兼容的问题吧。。。

**Comment by zhangboyang** [comment]
@ukhack 实在不行的话，也许可以试试从游侠网上下载安装对应的免CD补丁。

**Comment by zpliam** [comment]
新闻说了“‘重制版’人物场景都会重新建模”，所以整体画面形象应该是会朝4代之后的真人比例建模。不过我觉得要么从一代开始重制，要么从三外开始重制，应该不会一开始就重制三代。
现在用宽屏幕重玩三代真的超级开心！！！！！！超级感谢！！！！！真的辛苦了！！！！！！！！！！
也期待三外的补丁！！！三和三外都是入坑作，特别爱！！！！！！！！！！！！

**Comment by zhangboyang** [comment]
三外的补丁已经出测试版了，[下载地址](https://pal3.zbyzbyzby.com/pal3a)

**Comment by medivhna** [comment]
给大佬点赞
