### ISSUE TITLE
由0517版本更新到0717版本后报错

### ISSUE THREAD

**Issue by medivhna** [zhangboyang/PAL3patch#2]
运行主程序PAL3.exe报错：can't find config line with key 'fixhockshopbuy'

似乎和当铺修复有关？从原程序直接打补丁依旧报错。

**Comment by zhangboyang** [comment]
这是因为没有更新（覆盖）补丁配置文件PAL3patch.conf造成的。随着补丁升级，配置文件可能会有变动：20170530这版修复了当铺有时会卡住的bug，增加了一个新的选项。如果你想沿用旧的配置文件，你可以用记事本打开20170717这版的配置文件，把最后一行粘到旧配置文件最后就好了。

**Comment by medivhna** [comment]
你好，我看了一下，我的配置文件是覆盖了的，最后也存在这行配置，但是运行主程序仍然报错。

**Comment by medivhna** [comment]
我又试了一下0530版本，也是一样的报错

**Comment by zhangboyang** [comment]
那可能是UAC虚拟化的问题，你的仙剑三安装位置是哪里？是不是一个需要有管理员权限才能写的地方？

**Comment by zhangboyang** [comment]
0530的版本的配置文件和0717的是一样的。如果是UAC虚拟化的问题的话，你可以去C:\Users\***\AppData\Local\VirtualStore\下找找对应的位置是否也存在一份PAL3patch.conf

**Comment by medivhna** [comment]
是的，我注意到我的存档就存在VirtualStore目录下，应该就是这个问题

**Comment by medivhna** [comment]
正常了，thx

**Comment by medivhna** [comment]
我安装在C:\Program Files (x86)\PAL3目录下，这个目录需要管理员权限

**Comment by zhangboyang** [comment]
嗯，UAC虚拟化是一个容易让人疑惑的问题。。。我可能需要加点提示说明之类的。。。

**Comment by zhangboyang** [comment]
更新20170812版本后，类似问题可通过补丁配置工具中的“恢复默认配置”功能解决。
