### ISSUE TITLE
请问该补丁支持 win10 64位系统吗？

### ISSUE THREAD

**Issue by nizihabi** [zhangboyang/PAL3patch#3]
之前下载过1.04版的都提示需要插入CD，另外楼主知道有哪些提取游戏里面模型的工具吗_(:з」∠)_，想用仙三里面的模型做一些同人小游戏自娱自乐

**Comment by zhangboyang** [comment]
支持的呀～提取游戏模型方面我不大清楚，仙三的模型格式是他们自已搞的一套，之前有人分析过，但代码丢了，你可以参考一下这里的资料 [https://tieba.baidu.com/p/5381666939](https://tieba.baidu.com/p/5381666939)

**Comment by nizihabi** [comment]
噢噢~已经用上了！体验非常好！！！感谢楼主！另外看到了楼主的开发日志里面叙述的源码问题23333，已经编译了一版，12年前的感动用这种方式重现了QAQ PS：我用vs2013编译出来的引擎dll加载图片会有问题，最后用的发行版的dll解决的，请问楼主遇到了这问题吗？

**Comment by zhangboyang** [comment]
那份代码只是个内部的测试版本，我用VC6编译的，但我没怎么运行过（运行时会有很多问题，比如崩溃之类的），我一般只是拿来看而已。。。。
