### ISSUE TITLE
有兴趣想做游戏的英文翻译，不知道大神能不能合作一下。。。

### ISSUE THREAD

**Issue by Klavierbuchlein** [zhangboyang/PAL3patch#4]
如果技术上难度不是很大的话。

**Comment by zhangboyang** [comment]
你的意思是翻译游戏的内容？

**Comment by Klavierbuchlein** [comment]
是的。。。可能需要挺久，我也可能会找更多的人手。我一直觉得仙剑3是很高质量的RPG，很早前就有英化这游戏的想法了（10年多前）但没有技术。我觉得有英文版的话一定有不少欧美人会喜欢上。我的qq是1735336715, discord是 https://discord.gg/RXG6cD

**Comment by zhangboyang** [comment]
我仔细想了一下，大概会有以下几个技术问题：

1. 游戏内文字的提取（剧情、物品、UI等）及修改
2. 游戏模型贴图中文字的修改
3. 游戏内文字渲染需要为英文文字做优化

(1)可以采用“修改游戏脚本”或是”外挂汉化插件“，前者较理想；(3)可以通过制作插件完成。
游戏脚本的话，由于分辨率补丁与它没什么关系，所以我也不太清楚怎么改。。。做三高难的人应该有不少研究，你可以问问他们。。。

**Comment by Klavierbuchlein** [comment]
做三高难的人是谁？怎样联系他们？我在网上找过修改游戏脚本的的软件，但发现输入的文本不能超过原文（英文需要的字数会比中文高出很多）。。。

**Comment by neverwin** [comment]
你可以看下https://bbs.pediy.com/thread-157228.htm
