### ISSUE TITLE
dx90update_extras.exe

### ISSUE THREAD

**Issue by wobakj** [zhangboyang/PAL3patch#5]
Hello,

I was looking for the dx90update_extras.exe file online and found a reference to it in compile.txt
The file is not available anywhere else, do you still have it?

Regards,
Wobak

**Comment by zhangboyang** [comment]
Yes, you can download it from [here](https://drive.google.com/file/d/1bIsW5ygqT4VtoM1CLG2wXR6l4KVZIR1Q/view?usp=sharing).

**Comment by wobakj** [comment]
Thank you very much! Do you happen to have any other DirectX SDK extras or symbols? 
You could reply to my public mail if you dont want to fill this issue with unrelated discussion.

**Comment by zhangboyang** [comment]
[sha1sum.txt](https://github.com/zhangboyang/PAL3patch/files/2407806/sha1sum.txt)
This is my DirectX SDK collection. However the collection is very incomplete and the only extras that I have are "dx90update_extras.exe" and "dxsdk_sum2004_extras.exe".
If you want any of them, I can upload it for you.

**Comment by wobakj** [comment]
Could you upload the dx90asdk.exe? it seems like no one else was able to acquire it within the last couple of years.
I am in the process of creating a permanent collection of the SDKs on archive.org. With the 9a SDK, at least all SDKs will be permanently available. Most of the debug symbols seem to be lost however.

**Comment by zhangboyang** [comment]
[This](https://drive.google.com/file/d/1bKDpA4I7ek8OisSeTUNyBN5_4XaE0NYG/view?usp=sharing) is the dx90asdk.exe. In China, there is a download software called [Xunlei](https://en.wikipedia.org/wiki/Xunlei). I actually downloaded those files at around 2016 or 2017 with it. It operates a powerful P2P network and it can resolve many deadlinks. If you can give me the dead download link of what you want to download (offical links are better), I can have a try with it.

By the way, I remember that the SHA1 hashes of SDKs were retrieved from offical MSDN subscription download center, however it seems that it has been showdown at around 2017. I remember that it had a catalog of many many software (including DirectX SDKs). At that time, the hashes were public viewable in that site but the file dowload need MSDN subscription.

**Comment by wobakj** [comment]
Thanks! Your help is much appreciated.
[Here is a table of unavailable components that I know to exist.](https://docs.google.com/spreadsheets/d/1ZC2lKSHzpeSUCSG1SlmDaOf0S3URrUgwBx6YJ7IPLJE/edit?usp=sharing)
If a reference link leads to an offline/unavailable page, it must be accessed through waybackmachine.

**Comment by zhangboyang** [comment]
Sorry I tried Xunlei but it can't download any of them. I think these files are lost in public network.

**Comment by wobakj** [comment]
That is too bad. Regardless, thank you very much for having a look!
I can add a link to the collection here once I'm done uploading, in case you need some SDK in the future.
edit: [here is a link to the collection](https://archive.org/details/directxsdks)

**Comment by zhangboyang** [comment]
Thank you for providing your collection!
