### ISSUE TITLE
作者贴个收款码，我要发个红包感谢你！

### ISSUE THREAD

**Issue by wensonsmith** [zhangboyang/PAL3patch#7]
哈哈哈，这个工具太好用了，让我这个30岁的人瞬间回到了18岁高考完哪个夏天

那时候就一直没有通关，准备重来一次。

这熟悉的音乐和地图，美啊！

Thanks a lot for your work !

**Comment by zhangboyang** [comment]
哈哈，红包就不用啦，你的心意我收到啦～
