### ISSUE TITLE
1080p过场视频

### ISSUE THREAD

**Issue by MuyukiSakana** [zhangboyang/PAL3patch#8]
大佬打扰了！
我弄了套1080p过场视频（topaz那个工具+旧版radtool），所以把补丁里贴图尺寸改到2048x2048了，会影响其他界面吗？
顺便问下2DEFFECT里有用吗？没切比例，输出的1440x1080。
另外cpk超过2.3G（？）左右，超出的部分就读不出来了，movie.cpk没事，但movie_end.cpk超过了，只好重新bink设了个80%体积刚刚好，画质也还成。
对了黑边切了所以把适配注释掉测试的

**Comment by zhangboyang** [comment]
> 大佬打扰了！ 我弄了套1080p过场视频（topaz那个工具+旧版radtool），所以把补丁里贴图尺寸改到2048x2048了，会影响其他界面吗？ 

“贴图尺寸”是指视频的尺寸吗？还是指3D模型上的贴图的尺寸？

> 顺便问下2DEFFECT里有用吗？没切比例，输出的1440x1080。 

有用到的，如果在战斗界面使用灵珠，就会显示一段灵珠的动画

> 另外cpk超过2.3G（？）左右，超出的部分就读不出来了，movie.cpk没事，但movie_end.cpk超过了，只好重新bink设了个80%体积刚刚好，画质也还成。 对了黑边切了所以把适配注释掉测试的

这个可以在程序里处理绕过cpk那一套，直接调用磁盘上的文件。

---

之前也有人做过视频的高清化，但问题在于bik编码高清视频实在是太垃圾了，编码巨慢画质巨差而且文件巨大，一个“高清”视频补丁比N个游戏本体还大。如果用h264甚至h265会比bik好N倍。但如果把视频换成h264或h265需要重写播放的代码，相当于做一个播放器，我实在没时间写（主要是要考虑一堆问题：技术路线是选ffmpeg那一套还是directshow那一套；如何做音画同步；如何检测机器性能是否够解码视频并在性能弱的机器上优雅降级等等）。

**Comment by MuyukiSakana** [comment]
改的这里：
PAL3patch\src\PAL3patch\src\patch_nolockablebackbuffer.c
`// texture`
`#define MF_TEX_WIDTH 2048`
`#define MF_TEX_HEIGHT 2048`

**Comment by MuyukiSakana** [comment]
感谢大佬解答
不太会用GitHub

**Comment by zhangboyang** [comment]
> 改的这里： PAL3patch\src\PAL3patch\src\patch_nolockablebackbuffer.c `// texture` `#define MF_TEX_WIDTH 2048` `#define MF_TEX_HEIGHT 2048`

我印象里当时我找了个riva tnt2测试了一下1024x1024是没有问题的，改成2048x2048的话，根据微软的文档来看应该是没有问题，如果再大些可能就会有问题了，比如可能有的（古董）显卡不支持更大尺寸的贴图之类的

**Comment by MuyukiSakana** [comment]
感谢解答，麻烦您了
